//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.28 at 02:11:32 PM CET 
//


package app.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}mailprops"/&gt;
 *         &lt;element ref="{}urls"/&gt;
 *         &lt;element ref="{}filter"/&gt;
 *         &lt;element ref="{}recipients"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mailprops",
    "urls",
    "filter",
    "recipients"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    protected Mailprops mailprops;
    @XmlElement(required = true)
    protected Urls urls;
    @XmlElement(required = true)
    protected Filter filter;
    @XmlElement(required = true)
    protected Recipients recipients;

    /**
     * Gets the value of the mailprops property.
     * 
     * @return
     *     possible object is
     *     {@link Mailprops }
     *     
     */
    public Mailprops getMailprops() {
        return mailprops;
    }

    /**
     * Sets the value of the mailprops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mailprops }
     *     
     */
    public void setMailprops(Mailprops value) {
        this.mailprops = value;
    }

    /**
     * Gets the value of the urls property.
     * 
     * @return
     *     possible object is
     *     {@link Urls }
     *     
     */
    public Urls getUrls() {
        return urls;
    }

    /**
     * Sets the value of the urls property.
     * 
     * @param value
     *     allowed object is
     *     {@link Urls }
     *     
     */
    public void setUrls(Urls value) {
        this.urls = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setFilter(Filter value) {
        this.filter = value;
    }

    /**
     * Gets the value of the recipients property.
     * 
     * @return
     *     possible object is
     *     {@link Recipients }
     *     
     */
    public Recipients getRecipients() {
        return recipients;
    }

    /**
     * Sets the value of the recipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipients }
     *     
     */
    public void setRecipients(Recipients value) {
        this.recipients = value;
    }

}
